site_name: UANDESLAB - 3DPC

theme:
  name: material
  font:
    text: "Poppins"
    code: "JetBrains Mono"

  features:
    - content.code.copy



  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: amber
      accent: cyan
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: cyan
      primary: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra_css:
  - stylesheets/extra.css